name: my_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  english_words: ^4.0.0
  russian_words: ^0.2.0
  http: ^0.13.4
  flutter_slidable: ^3.0.0
  web_socket_channel: ^2.4.0
  mockito: ^5.4.2
  badges: ^3.1.1
  flutter_router: ^1.1.0
  flutter_spinkit: ^5.1.0
  convex_bottom_bar: ^3.0.0
  flutter_svg: ^0.22.0
  flutter_staggered_animations: ^1.1.1
  get: ^4.6.5
  flutter_facebook_auth: ^5.0.11
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
        - assets/images/
    # - ../assets/icons/
